apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: capa-adapter

resources:
  - ../../base
  - secretstore.yaml
  - externalsecret.yaml

images:
  - name: capa-adapter
    newName: 730335471935.dkr.ecr.us-east-2.amazonaws.com/capa-adapter
    newTag: latest

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: capa-adapter
  - target:
      kind: ConfigMap
      name: capa-adapter-config
    patch: |-
      - op: replace
        path: /data/ENV
        value: prod
      - op: replace
        path: /data/LOG_LEVEL
        value: info
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: capa.checker.finance
    target:
      kind: Ingress
      name: capa-adapter
