apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kiiex-adapter-dev

resources:
  - ../../base
  - secretstore.yaml
  - externalsecret.yaml

namePrefix: dev-

images:
  - name: kiiex-adapter
    newName: 730335471935.dkr.ecr.us-east-2.amazonaws.com/kiiex-adapter
    newTag: dev

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: kiiex-adapter-dev
    target:
      kind: Namespace
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: kiiex-adapter
  - target:
      kind: ConfigMap
      name: kiiex-adapter-config
    patch: |-
      - op: replace
        path: /data/ENV
        value: dev
      - op: replace
        path: /data/LOG_LEVEL
        value: debug
      - op: replace
        path: /data/KIIEX_WEBSOCKET_URL
        value: "wss://api.kiire.alphaprod.net/WSGateway"
