apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zodia-adapter-secrets
  namespace: zodia-adapter-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: zodia-adapter-secrets
    creationPolicy: Owner
    template:
      data:
        DATABASE_URL: "{{ .DATABASE_URL }}"
        REDIS_URL: "{{ .REDIS_URL }}"
        NATS_URL: "{{ .NATS_URL }}"
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: dev/zodia-adapter
        property: DATABASE_URL
    - secretKey: REDIS_URL
      remoteRef:
        key: dev/zodia-adapter
        property: REDIS_URL
    - secretKey: NATS_URL
      remoteRef:
        key: dev/zodia-adapter
        property: NATS_URL
