apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: b2c2-adapter-secrets
  namespace: b2c2-adapter
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: b2c2-adapter-secrets
    creationPolicy: Owner
    template:
      data:
        NATS_URL: "{{ .nats_url }}"
        LOG_LEVEL: "{{ .log_level }}"
  data:
    - secretKey: nats_url
      remoteRef:
        key: prod/b2c2-adapter
        property: nats_url
    - secretKey: log_level
      remoteRef:
        key: prod/b2c2-adapter
        property: log_level
