apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: b2c2-adapter-secrets
  namespace: b2c2-adapter
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: b2c2-adapter-secrets
    creationPolicy: Owner
    template:
      data:
        AMQP_URL: "{{ .AMQP_URL }}"
  data:
    - secretKey: AMQP_URL
      remoteRef:
        key: b2c2-adapter/prod
        property: AMQP_URL
