apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: b2c2-adapter

resources:
  - ../../base
  - secretstore.yaml
  - externalsecret.yaml

images:
  - name: b2c2-adapter
    newName: 730335471935.dkr.ecr.us-east-2.amazonaws.com/b2c2-adapter
    newTag: latest

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: b2c2-adapter
