apiVersion: v1
kind: ConfigMap
metadata:
  name: capa-adapter-config
  namespace: capa-adapter
data:
  SERVICE_NAME: "capa-adapter"
  ENV: "base"
  LOG_LEVEL: "info"
  CAPA_PORT: "9060"
  CAPA_POLL_INTERVAL: "30s"
  CACHE_TTL: "24h"
  CACHE_CLEANUP_FREQ: "10m"
  INBOUND_SUBJECT: "cmd.lp.quote_request.v1.CAPA"
  OUTBOUND_SUBJECT: "evt.lp.quote_response.v1.CAPA"
  TRADE_EXECUTE_SUBJECT: "cmd.lp.trade_execute.v1.CAPA"
  AWS_REGION: "us-east-2"
