apiVersion: v1
kind: Service
metadata:
  name: capa-adapter
  namespace: capa-adapter
spec:
  selector:
    app.kubernetes.io/name: capa-adapter
  ports:
    - name: http
      port: 9060
      targetPort: http
      protocol: TCP
  type: ClusterIP
