apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: b2c2-adapter-dev

resources:
  - ../../base
  - secretstore.yaml
  - externalsecret.yaml

namePrefix: dev-

images:
  - name: b2c2-adapter
    newName: 730335471935.dkr.ecr.us-east-2.amazonaws.com/b2c2-adapter
    newTag: dev

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: b2c2-adapter-dev
    target:
      kind: Namespace
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: b2c2-adapter
  - target:
      kind: ConfigMap
      name: b2c2-adapter-config
    patch: |-
      - op: replace
        path: /data/ENV
        value: dev
      - op: replace
        path: /data/LOG_LEVEL
        value: debug
      - op: replace
        path: /data/B2C2_DEFAULT_BASE_URL
        value: https://api.uat.b2c2.net
