apiVersion: v1
kind: ConfigMap
metadata:
  name: kiiex-adapter-config
  namespace: kiiex-adapter
data:
  SERVICE_NAME: "kiiex-adapter"
  ENV: "base"
  AWS_REGION: "us-east-2"
  LOG_LEVEL: "info"
  SERVER_PORT: "8082"
  KIIEX_WEBSOCKET_URL: "wss://api.kiire.alphaprod.net/WSGateway"
  CACHE_TTL: "24h"
  KIIEX_INBOUND_SUBJECT: "cmd.lp.trade_execute.v1.KIIEX"
  KIIEX_CANCEL_SUBJECT: "cmd.lp.trade_cancel.v1.KIIEX"
