apiVersion: v1
kind: Service
metadata:
  name: kiiex-adapter
  namespace: kiiex-adapter
spec:
  selector:
    app.kubernetes.io/name: kiiex-adapter
  ports:
    - name: health
      port: 8082
      targetPort: health
      protocol: TCP
