apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zodia-adapter-secrets
  namespace: zodia-adapter
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: zodia-adapter-secrets
    creationPolicy: Owner
    template:
      data:
        DATABASE_URL: "{{ .DATABASE_URL }}"
        REDIS_PASS: "{{ .REDIS_PASS }}"
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: zodia-adapter/prod
        property: DATABASE_URL
    - secretKey: REDIS_PASS
      remoteRef:
        key: zodia-adapter/prod
        property: REDIS_PASS
